"""Add collection_rag to ConfiguracaoNegocio
Revision ID: b7c0618d7931
Revises: 20251126_add_server_defaults
Create Date: 2025-11-28 02:32:19.401899

"""

# revision identifiers, used by Alembic.
revision = "b7c0618d7931"
down_revision = "20251126_add_server_defaults"
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuracao_negocio", sa.Column("collection_rag", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuracao_negocio", "collection_rag")
    # ### end Alembic commands ###
