"""Expande o schema para onboarding completo de clientes

Revision ID: c1228bec62c3
Revises: 
Create Date: 2025-09-25 20:15:31.073376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1228bec62c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_vizu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('clientes_finais_metadados',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('id_externo_cliente_final', sa.String(length=255), nullable=False),
    sa.Column('dados_customizados', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('id_usuario_final', sa.String(length=255), nullable=False),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fontes_de_dados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('tipo_fonte', sa.String(length=50), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=False),
    sa.Column('status_indexacao', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversa_id', sa.UUID(), nullable=False),
    sa.Column('remetente', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('timestamp_envio', sa.DateTime(), nullable=True),
    sa.Column('metadados_ia', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    op.drop_table('fontes_de_dados')
    op.drop_table('conversas')
    op.drop_table('clientes_finais_metadados')
    op.drop_table('clientes_vizu')
    # ### end Alembic commands ###
