"""Cria a estrutura de tabelas inicial do sistema

Revision ID: eb9cc2d0c260
Revises: c1228bec62c3
Create Date: 2025-09-29 14:29:32.867032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb9cc2d0c260'
down_revision: Union[str, Sequence[str], None] = 'c1228bec62c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_finais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('metadados', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_vizu_id', 'id_externo', name='_cliente_vizu_id_externo_uc')
    )
    op.create_table('configuracoes_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('prompt_base', sa.Text(), nullable=False),
    sa.Column('horario_funcionamento', sa.JSON(), nullable=True),
    sa.Column('ferramenta_rag_habilitada', sa.Boolean(), nullable=True),
    sa.Column('ferramenta_agendamento_habilitada', sa.Boolean(), nullable=True),
    sa.Column('ferramenta_consulta_db_habilitada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_vizu_id')
    )
    op.create_table('credenciais_servicos_externos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), nullable=False),
    sa.Column('nome_servico', sa.String(length=100), nullable=False),
    sa.Column('credenciais_cifradas', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_vizu_id', 'nome_servico', name='_cliente_servico_uc')
    )
    op.drop_table('clientes_finais_metadados')
    op.add_column('conversas', sa.Column('cliente_final_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('conversas_cliente_vizu_id_fkey'), 'conversas', type_='foreignkey')
    op.create_foreign_key(None, 'conversas', 'clientes_finais', ['cliente_final_id'], ['id'])
    op.drop_column('conversas', 'cliente_vizu_id')
    op.drop_column('conversas', 'id_usuario_final')
    op.alter_column('mensagens', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mensagens', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('conversas', sa.Column('id_usuario_final', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('conversas', sa.Column('cliente_vizu_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversas', type_='foreignkey')
    op.create_foreign_key(op.f('conversas_cliente_vizu_id_fkey'), 'conversas', 'clientes_vizu', ['cliente_vizu_id'], ['id'])
    op.drop_column('conversas', 'cliente_final_id')
    op.create_table('clientes_finais_metadados',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cliente_vizu_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_externo_cliente_final', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dados_customizados', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_vizu_id'], ['clientes_vizu.id'], name=op.f('clientes_finais_metadados_cliente_vizu_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clientes_finais_metadados_pkey'))
    )
    op.drop_table('credenciais_servicos_externos')
    op.drop_table('configuracoes_negocio')
    op.drop_table('clientes_finais')
    # ### end Alembic commands ###
